// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgM5IRyMBPgUJwhLG0H-rTAX3t1LNqw8s',
    appId: '1:342554237617:web:884785339afb45d2a5e090',
    messagingSenderId: '342554237617',
    projectId: 'project-jarvis-b8dbe',
    authDomain: 'project-jarvis-b8dbe.firebaseapp.com',
    storageBucket: 'project-jarvis-b8dbe.firebasestorage.app',
    measurementId: 'G-0HTVRTHHYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMCwZsdEXMtsASUihB4Whm3i74geC_lj0',
    appId: '1:342554237617:android:a131c974c7280500a5e090',
    messagingSenderId: '342554237617',
    projectId: 'project-jarvis-b8dbe',
    storageBucket: 'project-jarvis-b8dbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr6zEsHgAnUVtBHqPRQG4V82bGc5WKUgc',
    appId: '1:342554237617:ios:de28dc5f277d8cf9a5e090',
    messagingSenderId: '342554237617',
    projectId: 'project-jarvis-b8dbe',
    storageBucket: 'project-jarvis-b8dbe.firebasestorage.app',
    iosBundleId: 'com.example.projectJarvis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr6zEsHgAnUVtBHqPRQG4V82bGc5WKUgc',
    appId: '1:342554237617:ios:de28dc5f277d8cf9a5e090',
    messagingSenderId: '342554237617',
    projectId: 'project-jarvis-b8dbe',
    storageBucket: 'project-jarvis-b8dbe.firebasestorage.app',
    iosBundleId: 'com.example.projectJarvis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgM5IRyMBPgUJwhLG0H-rTAX3t1LNqw8s',
    appId: '1:342554237617:web:9667bdc5c7a09345a5e090',
    messagingSenderId: '342554237617',
    projectId: 'project-jarvis-b8dbe',
    authDomain: 'project-jarvis-b8dbe.firebaseapp.com',
    storageBucket: 'project-jarvis-b8dbe.firebasestorage.app',
    measurementId: 'G-DPQF0XM1QL',
  );
}
